# tiny thing - you should be able to provide a name when you generate migrations
# e.g.: ./manage.py makemigrations <app_name> --name='add_lick_model'
# That way, they don't just all say 'auto', and it's easier to see which does what

# Generated by Django 2.1.5 on 2019-01-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppypost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='api.PuppyPost'),
        ),
    ]
