# Generated by Django 2.1.5 on 2019-01-17 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190116_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
