# Generated by Django 2.1.5 on 2019-01-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190117_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lick',
            old_name='liked_by',
            new_name='licked_by',
        ),
    ]
